#!/usr/bin/env zsh

PREZTO_HOME="$HOME/.zprezto"
DOTFILES_HOME="$HOME/.dotfiles"
LOCAL_BIN_DIR="$HOME/.local/bin"


function install_dotfiles() {
  git clone https://github.com/nossal/dotfiles "$DOTFILES_HOME"

  zsh_confs=(zpreztorc zprofile zshrc)  # Custom prezto confs.

  for rcfile in $zsh_confs; do
    ln -s "$DOTFILES_HOME/zsh/$rcfile" "$HOME/.$rcfile"
  done
}

function install_prezto() {
  git clone --recursive https://github.com/sorin-ionescu/prezto.git "$PREZTO_HOME"

  prezto_confs=(zlogin zshenv zlogout)

  for rcfile in $prezto_confs; do
    ln -s "$PREZTO_HOME/runcoms/$rcfile" "$HOME/.$rcfile"
  done
}

if [[ -a $PREZTO_HOME ]]; then
  echo "update PREZTO"
else
  echo "install PREZTO"
fi

if [[ -a $DOTFILES_HOME ]]; then
  echo "update DOTFILES"
else
  echo "install PREZTO"
fi

if [[ ! -a $LOCAL_BIN_DIR ]]; then
  mkdir -p $LOCAL_BIN_DIR
  cp
fi
