#!/usr/bin/env zsh

PREZTO_HOME="$HOME/.zprezto"
DOTFILES_HOME="$HOME/.dotfiles"

function install_dotfiles() {
  git clone https://github.com/nossal/dotfiles "$DOTFILES_HOME"

  zsh_confs=(zpreztorc zprofile zshrc)

  for rcfile in $zsh_confs; do
    ln -s "$DOTFILES_HOME/zsh/$rcfile" "$HOME/.$rcfile"
  done
}

function install_prezto() {
  git clone --recursive https://github.com/sorin-ionescu/prezto.git "$PREZTO_HOME"

  prezto_confs=(zlogin zshenv zlogout)

  for rcfile in $prezto_confs; do
    ln -s "$PREZTO_HOME/runcoms/$rcfile" "$HOME/.$rcfile"
  done
}

if [[ -a $PREZTO_HOME ]]; then
  echo "exists"
fi

if [[ -a $DOTFILES_HOME ]]; then
  echo "exists"
fi
