
# A minimal left prompt
format = """
$directory
$character
"""

continuation_prompt = "[▶](242) "
add_newline = false

# move the rest of the prompt to the right
right_format = """
$git_branch\
$git_status\
$git_state\
$java\
$python\
$rust\
$nodejs\
$lua\
$ocaml\
$c\
$battery\
$hostname
"""

palette = "nsl"

[palettes.nsl]
git_br_bg = "#25120c"
lang_bg = "#1e1e2e"
lang_icon_bg = "#28283d"


[directory]
truncation_length = 10
truncation_symbol = "…/"
truncate_to_repo = false
fish_style_pwd_dir_length = 5
repo_root_style = "bold yellow"
style = "066"

[directory.substitutions]
"~/.dotfiles/" = "[dotfiles]/"
"~/workspace/corp/" = "[corpo]/" # 


[character]
success_symbol = "[󰞷 ](fg:green bold bg:#000000)" # 󰞷 
error_symbol = "[](fg:red bold bg:#000000)"
vicmd_symbol = "[ ](fg:green bold bg:#000000)"

[battery]
full_symbol = "l "
charging_symbol = "󰂄 "
discharging_symbol = " "

[[battery.display]]
threshold = 20
style = "red italic"

[hostname]
ssh_only = true
ssh_symbol = "󰌘 " # 
format = ' [$ssh_symbol](bg:#351513 fg:#ffb400 bold italic)[ $hostname ](bg:#351513 fg:#f54d27 bold italic)'
# trim_at = '.local'
aliases = { "MacBook Pro" = "MACADMWT64WH0" }

[git_branch]
format = "[ $symbol$branch(:$remote_branch)]($style)"
symbol = " " #  
style = "bg:git_br_bg fg:#f54d27 italic"

[git_status]
format ="[ $all_status$ahead_behind]($style)"
behind = " ${count}"
ahead = " ${count} "
diverged = " ⇡${ahead_count}⇣${behind_count}"
modified = " ${count} "# " " 
untracked = "[${count}](bg:git_br_bg fg:#d31f00 italic) " #  A
deleted = " ${count} " # ""#"✘"
stashed = " ${count} "
up_to_date = "[ ](bg:git_br_bg fg:green italic)"#"" #"" #"" #""
staged = '[++$count](bg:git_br_bg fg:green italic) '
style = "bg:git_br_bg 208 italic"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[  PICKING](italic red)" # 🍒

[java]
format = " [ ${symbol} ](bg:#171936 fg:#e76f00)[ (${version} )]($style)"
version_format ="${major}.${minor}"
style = "fg:#437291 bg:#111429 italic"
symbol = ""

[python]
format = '[( $virtualenv:)]($style fg:028)[ ${symbol}]($style fg:#3776ab)[${version} ]($style)'
version_format ="${raw}"
symbol = " "
style = "fg:#ffd343 bg:lang_bg italic"

[rust]
format = "[ ${symbol}(${version} )]($style)"
version_format ="${raw}"
symbol = " "
style = "fg:#f44a00 bg:lang_bg italic"

[nodejs]
format = "[ ${symbol}(${version} )]($style)"
version_format ="${raw}"
symbol = " "
style = "fg:#2443b5 bg:lang_bg italic"

[lua]
format = "[ ${symbol}(${version} )]($style)"
version_format ="${raw}"
symbol = " "
style = "fg:#2443b5 bg:lang_bg italic"

[ocaml]
format = " [($switch_indicator:$switch_name) ${symbol}(${version} )]($style)"
symbol = " "
style = "fg:#ef7f06 bg:#2e1407 italic"
version_format = '${raw}'

[c]
format = "[ ${symbol}(${version} )]($style)"
version_format ="${raw}"
symbol = " "
style = "fg:#2443b5 bg:lang_bg italic"

