#!/usr/bin/env bash

source "$DOTDIR/bin/dot"

setup() {
  export MISE_INSTALL_HELP=0
  export MISE_QUIET=1

  curl -sL https://mise.run | sh && \
    mise tools up && \
    mise completion "$SHELL_NAME" > "$DOTDIR/shell/$SHELL_NAME/completions/_mise"
}

update() {
  mise self-update -y
  mise tools up
}

install "mise"
