#!/usr/bin/env bash

source "$DOTDIR/bin/dot"

function setup() {
  local target os

  os="$(os_name)"
  echo "$os"

  target="$HOME/.local/share/fonts"

  [ "$os" = "mac" ] && \
    target="$HOME/Library/Fonts"

  [ "$(is_wsl)" = true ] && \
    target="/mnt/c/Users/$(username)/AppData/Local/Microsoft/Windows/Fonts"

  [ ! -e "$target" ] && \
    mkdir -p "$target"

  echo "$target"
  cp -rf "$DOTDIR/fonts/fonts/." "$target"

  [ "$os" = "mac" ] && \
  fc-cache -v &>/dev/null
}

check() {
  return 0
}

update=setup
install "check" "Fonts"
