#/* vim: set filetype=zsh : */
typeset -gU path

path=(
  $HOME/.local/bin(N)
  $HOME/.dotfiles/bin(N)
  $HOME/.cargo/bin(N)
  $HOME/.atuin/bin(N)
  /opt/{homebrew,local}/{,s}bin(N)
  /usr/local{,s}bin(N)
  $HOME/go/bin(N)
  $JAVA_HOME/bin
  $path
)

