# vi: ft=zsh

export EDITOR="$(command -v nvim || command -v vi)"
export JAVA_HOME=$($HOME/.local/bin/mise where java)

typeset -gU path

path=(
  /usr/local{,s}bin(N)
  /opt/{homebrew,local}/{,s}bin(N)
  $HOME/.local/bin(N)
  $HOME/.dotfiles/bin(N)
  $HOME/.atuin/bin(N)
  $path
)

eval "$($HOME/.local/bin/mise activate zsh)"
# eval "$($HOME/.local/bin/mise activate zsh --shims)"
