export LANG=en_US.UTF-8
export DOTDIR=$HOME/.dotfiles
export ZSHDOTDIR=$DOTDIR/shell/zsh
export EDITOR=nvim
export GPG_TTY=$(tty)
export JAVA_HOME=$($HOME/.local/bin/mise where java)

WORK_DOTDIR="$DOTDIR-work"
[ -d $WORK_DOTDIR ] && source $WORK_DOTDIR/env.sh

