# .zshrc is sourced in interactive shells.
# It should contain commands to set up aliases,
# functions, options, key bindings, etc.

source $ZSHDOTDIR/functions.zsh
source $ZSHDOTDIR/editor.zsh
source $ZSHDOTDIR/../aliases

#allow tab completion in the middle of a word
setopt COMPLETE_IN_WORD

## keep background processes at full speed
setopt NOBGNICE
## restart running processes on exit
#setopt HUP

## history
setopt APPEND_HISTORY
setopt INC_APPEND_HISTORY
setopt BANG_HIST                 # Treat the '!' character specially during expansion.
setopt EXTENDED_HISTORY          # Write the history file in the ':start:elapsed;command' format.
setopt SHARE_HISTORY             # Share history between all sessions.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire a duplicate event first when trimming history.
setopt HIST_IGNORE_DUPS          # Do not record an event that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS      # Delete an old recorded event if a new event is a duplicate.
setopt HIST_FIND_NO_DUPS         # Do not display a previously found event.
setopt HIST_IGNORE_SPACE         # Do not record an event starting with a space.
setopt HIST_SAVE_NO_DUPS         # Do not write a duplicate event to the history file.
setopt HIST_VERIFY               # Do not execute immediately upon history expansion.
setopt HIST_BEEP                 # Beep when accessing non-existent history.

HISTFILE="${HISTFILE:-${ZDOTDIR:-$HOME}/.zsh_history}"
HISTSIZE=10000
SAVEHIST=$HISTSIZE

## never ever beep ever
setopt NO_BEEP

## directories
setopt AUTO_CD              # Auto changes to a directory without typing cd.
setopt AUTO_PUSHD           # Push the old directory onto the stack on cd.
setopt PUSHD_IGNORE_DUPS    # Do not store duplicates in the stack.
setopt PUSHD_SILENT         # Do not print the directory stack after pushd or popd.
setopt PUSHD_TO_HOME        # Push to home directory when no argument is given.
setopt CDABLE_VARS          # Change directory to a path stored in a variable.
setopt MULTIOS              # Write to multiple descriptors.
setopt EXTENDED_GLOB        # Use extended globbing syntax.
unsetopt CLOBBER            # Do not overwrite existing files with > and >>.
                            # Use >! and >>! to bypass.
## disable mail checking
MAILCHECK=0

# completions=(
#   "zsh-users/zsh-completions"
# )
for completion in $completions; do
  zsh_add_completion $completion
done

fpath+="$ZSHDOTDIR/completions"

zstyle ':completion:*:git-checkout:*' sort false
zstyle ':completion:*:descriptions' format '[%d]'
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' menu no

autoload -U +X compinit && compinit
autoload -U +X bashcompinit && bashcompinit

autoload -U colors

# Plugins
source $ZSHDOTDIR/plug.zsh
plugins=(
  "Aloxaf/fzf-tab"
  "z-shell/F-Sy-H"
  "zsh-users/zsh-autosuggestions"
  "hlissner/zsh-autopair"
)
load_plugins $plugins;

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#444"

# zstyle ':fzf-tab:complete:cd:*' fzf-preview 'ls --color $realpath'
zstyle ':fzf-tab:*' fzf-command ftb-tmux-popup

# TODO: custom fzf theme
# https://github.com/junegunn/fzf/wiki/Color-schemes

# The Prompt
eval "$(starship init zsh)"

eval "$($HOME/.local/bin/mise activate zsh)"
eval "$($HOME/.local/bin/mise activate zsh --shims)"
eval "$(zoxide init zsh)"
eval "$(atuin init zsh)"

# Set up fzf key bindings and fuzzy completion
source <(fzf --zsh)

