#!/usr/bin/env bash

set -e

ME="$(whoami)"

if [[ ! $(dnf repolist) == *'rpmfusion'* ]]; then
  sudo dnf -y install \
    https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-"$(rpm -E %fedora)".noarch.rpm;
  sudo dnf -y install \
    https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-"$(rpm -E %fedora)".noarch.rpm
fi

sudo dnf update

sudo dnf -y install zsh git neovim tmux pinentry-tty

sudo chsh -s /bin/zsh "$ME"
