#!/usr/bin/env bash

source "$DOTDIR/bin/dot"

setup() {
  # Install Tmux Plugin Manager (TPM)
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
}

check() {
  return 0
}

update=setup
install "check" "Tmux"
