#/* vim: set filetype=zsh : */
typeset -gU path

JAVA=$($HOME/.local/bin/mise where java)/bin

path=(
    $HOME/.local/bin(N)
    $HOME/{,s}bin(N)
    /opt/{homebrew,local}/{,s}bin(N)
    /usr/local{,s}bin(N)
    $HOME/go/bin(N)
    $JAVA
    $path
)
