#!/usr/bin/env bash

if has nvim; then
  echo "tem nvim"
  return
fi

case "$(os_name)" in
 "mac")
   brew install neovim
 ;;
 "fedora")
   sudo dnf install -y neovim
 ;;
 *)
   local_share_dir="$HOME/.local/share/"
   tmp_dir="$(mktemp -d)"
   curl -sSL https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz -o "$tmp_dir/nvim.tar.gz"
   tar -C "$local_share_dir" -xzf "$tmp_dir/nvim.tar.gz"
   ln -s "$local_share_dir/nvim-linux-x86_64/bin/nvim" "$LOCAL_BIN_DIR/nvim"
   rm -rf "$tmp_dir"
 ;;
esac
